// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GinpayFactory
{
    internal sealed partial class Vsix
    {
        public const string Id = "GinpayFactory.a2eadd8e-49d0-4ac8-869d-68ec580b5258";
        public const string Name = "GinpayFactory";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ginpay Iwatobi";
        public const string Tags = "";
    }
}
