// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace GinpayFactory
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GinpayFactoryString = "773d7868-2bb7-4fc4-9df8-4b6dc12c2de2";
        public static Guid GinpayFactory = new Guid(GinpayFactoryString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int SexyCommand = 0x0200;
        public const int GenkokuCommand = 0x0300;
    }
}